name: "CalVer to SemVer Release"
description: "Computes next SemVer release values."
inputs:
  calver:
    description: "Current CalVer"
    required: true
  calver-count:
    description: "Total number of existing CalVer's"
    required: true
  latest-semver:
    description: "Target repository's latest SemVer release"
    required: true
outputs:
  semver:
    description: "Computed SemVer"
    value: ${{ steps.format-results.outputs.semver }}
  notes:
    description: "Computed notes"
    value: ${{ steps.format-results.outputs.notes }}
runs:
  using: "composite"
  steps:
    - name: Parse latest SemVer release
      id: parse-latest-release
      run: |
        echo "minor<<EOF" >> $GITHUB_ENV
        echo "$(if [[ $(echo ${{ inputs.latest-semver }} | cut -d. -f2) ]]; then echo $(echo ${{ inputs.latest-semver }} | cut -d. -f2); else echo 0; fi)" >> $GITHUB_ENV        
        echo "EOF" >> $GITHUB_ENV
        echo "patch<<EOF" >> $GITHUB_ENV
        echo "$(if [[ $(echo ${{ inputs.latest-semver }} | cut -d. -f3) ]]; then echo $(echo ${{ inputs.latest-semver }} | cut -d. -f3); else echo 0; fi)" >> $GITHUB_ENV        
        echo "EOF" >> $GITHUB_ENV
      shell: bash
    - name: Normalize values
      id: normalize-values
      run: |
        echo "calver-count<<EOF" >> $GITHUB_ENV
        echo "$(expr ${{ inputs.calver-count }} - 1)" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV      
        echo "minor-count<<EOF" >> $GITHUB_ENV
        echo "$(if [[ -z ${{ env.minor }} ]]; then echo 0; else echo ${{ env.minor }}; fi)" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV
      shell: bash
    - name: Output SemVer release values
      id: format-results
      run: |
        echo "::set-output name=semver::1.${{ env.calver-count }}.$(if [[ ${{ env.calver-count }} -eq ${{ env.minor-count }} ]]; then echo $(expr ${{ env.patch }} + 1); else echo 0; fi)"
        echo "::set-output name=notes::$(if [[ ${{ env.calver-count }} -eq ${{ env.minor-count }} ]]; then echo Made minor changes for ${{ inputs.calver }}; else echo Made major changes for ${{ inputs.calver }}; fi)"
      shell: bash
